INSERT INTO recipe(id, name, people) VALUES(1, 'Baked Omelet With Broccoli & Tomato', 4);
INSERT INTO ingredient(id, name) VALUES(1, 'milk');
INSERT INTO ingredient(id, name) VALUES(2, 'cottage cheese');
INSERT INTO ingredient(id, name) VALUES(3, 'broccoli');
INSERT INTO ingredient(id, name) VALUES(4, 'cheddar cheese');
INSERT INTO ingredient(id, name) VALUES(5, 'basil');
INSERT INTO ingredient(id, name) VALUES(6, 'onion powder');
INSERT INTO ingredient(id, name) VALUES(7, 'eggs');
INSERT INTO ingredient(id, name) VALUES(8, 'garlic powder');
INSERT INTO ingredient(id, name) VALUES(9, 'roma tomato');
INSERT INTO ingredient(id, name) VALUES(10, 'salt');
